'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { dashboardApi, connectorUrl } from '../../lib/online-dashboard';
import { Icon } from './icon';
type Row = { itemId: number; name: string; sku: string; stock: number | null; status: string; hasModel: boolean };
export default function CommerceOverview({ mode = 'overview' }: { mode?: 'overview' | 'inventory' | 'settings' }) {
  const [products, setProducts] = useState<Row[]>([]), [orders, setOrders] = useState<{ status: string; orderSn: string }[]>([]), [syncedAt, setSyncedAt] = useState<number | null>(null), [syncStatus, setSyncStatus] = useState('never');
  const [error, setError] = useState(''), [orderError, setOrderError] = useState(''), [loading, setLoading] = useState(true), [more, setMore] = useState(false), [query, setQuery] = useState(''), [stockFilter, setStockFilter] = useState('low'), [page, setPage] = useState(0);
  async function refresh() {
    setLoading(true); setError(''); setOrderError('');
    const results = await Promise.allSettled([dashboardApi('/products'), ...(mode === 'overview' ? [dashboardApi('/orders')] : [])]);
    const productResult = results[0];
    if (productResult?.status === 'fulfilled') { setProducts(productResult.value.products); setSyncedAt(productResult.value.syncedAt); setSyncStatus(productResult.value.syncStatus); } else if (productResult?.status === 'rejected') setError(productResult.reason.message);
    const orderResult = results[1]; if (orderResult?.status === 'fulfilled') { setOrders(orderResult.value.orders); setMore(orderResult.value.hasNextPage); } else if (orderResult?.status === 'rejected') setOrderError(orderResult.reason.message);
    setLoading(false);
  }
  useEffect(() => { void refresh(); }, [mode]); // Data is reloaded when switching workspace sections.
  const low = products.filter(p => p.stock !== null && p.stock > 0 && p.stock <= 10);
  const empty = products.filter(p => p.stock === 0);
  const filtered = products.filter(p => `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase()) && (stockFilter === 'all' || (stockFilter === 'empty' ? p.stock === 0 : p.stock !== null && p.stock > 0 && p.stock <= 10)));
  const visiblePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / 20) - 1));
  const date = syncedAt ? new Date(syncedAt).toLocaleString('id-ID') : 'Belum ada sinkronisasi';
  const statuses = [['READY_TO_SHIP', 'Siap dikirim', 'amber'], ['PROCESSED', 'Menunggu kurir', 'blue'], ['SHIPPED', 'Dalam pengiriman', 'violet'], ['COMPLETED', 'Selesai', 'green']];
  return <section className="commerce-page">
    <div className="commerce-page-heading"><div><span className="commerce-eyebrow">SHOPEE WORKSPACE</span><h1>{mode === 'inventory' ? 'Pantauan stok' : mode === 'settings' ? 'Integrasi toko' : 'Ringkasan operasional'}</h1><p>{mode === 'inventory' ? 'Temukan produk yang perlu diisi ulang sebelum stok habis.' : mode === 'settings' ? 'Kelola koneksi dan akses ke toko Shopee Anda.' : 'Semua pekerjaan toko, dalam satu pandangan.'}</p></div><button className="commerce-button" onClick={refresh} disabled={loading}>{loading ? 'Memuat…' : '↻ Perbarui data'}</button></div>
    {error && <p role="alert" className="form-error">{error}</p>}
    <div className="commerce-sync-strip"><span className="commerce-dot"/><strong>Data produk tersimpan</strong><span>{date}</span><span className="commerce-status-tag">{syncStatus === 'ok' ? 'Sinkronisasi selesai' : syncStatus === 'running' ? 'Sinkronisasi berjalan' : 'Periksa sinkronisasi'}</span></div>
    {mode === 'settings' ? <><div className="commerce-card integration-card"><div className="commerce-card-heading"><div><h2>Toko yang terhubung</h2><p>Akses operasional dikelola melalui akun pemilik.</p></div><span className="shopee-mark">S</span></div><dl><dt>Marketplace</dt><dd>Shopee Indonesia</dd><dt>Shop ID</dt><dd>59604858</dd><dt>Produk tersimpan</dt><dd>{loading ? '…' : products.length}</dd><dt>Sinkronisasi terakhir</dt><dd>{date}</dd><dt>Pembaruan produk</dt><dd>Otomatis setiap 5 menit saat konektor aktif</dd></dl><a className="commerce-button primary" href={connectorUrl} target="_blank" rel="noreferrer">Buka konektor / Otorisasi ulang ↗</a></div><div className="commerce-card"><h2>Cakupan workspace</h2><p>Produk, harga dan stok produk tanpa variasi, paket dan kurir, pengiriman, serta dokumen resi menggunakan integrasi Shopee. Akses tiap operasi mengikuti izin aplikasi dan status pesanan.</p><p>Pengelolaan pembelian supplier, iklan, chat, retur, dan rekonsiliasi keuangan belum tersedia di workspace ini.</p><p>Jumlah produk tersimpan tidak membuktikan koneksi saat ini masih aktif. Jika sinkronisasi ditolak, buka konektor untuk memeriksa otorisasi.</p></div></> : <>
    <div className="commerce-metrics">{[[products.length, 'Produk tersimpan', 'box', 'blue'], [products.filter(p => p.status === 'NORMAL').length, 'Produk aktif', 'shop', 'green'], [low.length, 'Stok menipis', 'chart', 'amber'], [empty.length, 'Stok habis', 'box', 'red']].map(([n, label, icon, color]) => <div className="commerce-metric" key={label}><span className={`metric-icon ${color}`}><Icon name={String(icon)} size={21}/></span><div><small>{label}</small><strong>{loading ? '—' : Number(n).toLocaleString('id-ID')}</strong></div></div>)}</div>
    {mode === 'overview' && <><div className="commerce-card"><div className="commerce-card-heading"><div><h2>Alur pesanan</h2><p>Pesanan dibuat dalam 14 hari terakhir · {more ? '50 pesanan pada halaman pertama; bukan total seluruh pesanan' : `${orders.length} pesanan dimuat`}</p></div><Link href="/panel/product/orders">Lihat pesanan →</Link></div>{orderError ? <p role="alert" className="form-error">{orderError}</p> : <div className="commerce-order-flow">{statuses.map(([key,label,color],i) => <Link key={key} href={`/panel/product/orders?status=${key}`}><span className={`flow-number ${color}`}>{i+1}</span><span>{label}<strong>{loading ? '—' : orders.filter(o => o.status === key).length}</strong></span><span className="flow-arrow">›</span></Link>)}</div>}</div><div className="commerce-quick-grid">{[['Kelola produk','Perbarui harga, stok, paket dan kurir.','box','/panel/product/mp/shopee'],['Proses pesanan','Siapkan pickup atau drop-off paket.','order','/panel/product/orders'],['Dokumen pengiriman','Siapkan dan unduh resi PDF.','bag','/panel/product/shipping']].map(([title,desc,icon,url])=><Link key={title} href={url!} className="commerce-quick"><Icon name={icon!} size={25}/><div><h3>{title}</h3><p>{desc}</p></div><span>↗</span></Link>)}</div></>}
    <div className="commerce-card"><div className="commerce-card-heading"><div><h2>{mode === 'inventory' ? 'Daftar stok produk' : 'Produk yang perlu perhatian'}</h2><p>Stok menipis: 1–10 unit tersedia. Stok produk variasi perlu diperiksa per variasi di Seller Centre.</p></div>{mode === 'overview' && <Link href="/panel/inventory">Lihat semua →</Link>}</div><div className="commerce-filter-row"><input aria-label="Cari stok" placeholder="Cari nama produk atau SKU" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><select aria-label="Filter stok" value={stockFilter} onChange={e=>{setStockFilter(e.target.value);setPage(0);}}><option value="low">Stok menipis</option><option value="empty">Stok habis</option><option value="all">Semua produk</option></select></div><div className="live-table-wrap"><table className="live-table"><thead><tr><th>Produk</th><th>SKU</th><th>Stok tersedia</th><th>Tindakan</th></tr></thead><tbody>{filtered.slice(visiblePage*20,(visiblePage+1)*20).map(p=><tr key={p.itemId}><td><strong>{p.name}</strong><small>{p.hasModel ? 'Produk variasi' : 'Produk tanpa variasi'}</small></td><td>{p.sku || '—'}</td><td><span className={p.stock===0?'stock-empty':p.stock!==null&&p.stock<=10?'stock-low':''}>{p.stock ?? 'Tidak tersedia'}</span></td><td><Link href={`/panel/product/mp/shopee?q=${p.itemId}`}>Kelola produk →</Link></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="commerce-empty"><Icon name="box" size={32}/><h3>Tidak ada produk pada filter ini</h3><p>Ubah filter atau sinkronkan produk dari halaman Produk online.</p></div>}<div className="commerce-pagination"><span>{filtered.length} produk</span><button disabled={visiblePage===0} onClick={()=>setPage(visiblePage-1)}>← Sebelumnya</button><span>{visiblePage+1} / {Math.max(1,Math.ceil(filtered.length/20))}</span><button disabled={(visiblePage+1)*20>=filtered.length} onClick={()=>setPage(visiblePage+1)}>Berikutnya →</button></div></div></>}
  </section>;
}
