'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { dashboardApi } from '../../lib/online-dashboard';
import { downloadCsv } from '../../lib/commerce-export';
import { Modal } from './ui';
type Master = { id: string; sku: string; name: string; variant: string; shopSku: string; itemId: number; modelId: number; locationId: string; stock: number; observedStock: number; observedAt: number; version: number; status: string; message?: string; source: string };
type Candidate = { itemId: number; modelId: number; locationId: string; name: string; variant: string; shopSku: string; stock: number };
type Product = { itemId: number; name: string; sku: string };
type ImportRow = { sku: string; previous: number; stock: number; name: string; changed: boolean };
const statusText: Record<string,string> = { synced: 'Sesuai Shopee', queued: 'Dalam antrean', processing: 'Sedang dikirim', review: 'Perlu ditinjau' };
export default function MasterProducts() {
  const [rows,setRows]=useState<Master[]>([]),[products,setProducts]=useState<Product[]>([]),[imports,setImports]=useState<any[]>([]),[worker,setWorker]=useState<{lastRunAt:number|null;lastError:string|null}>({lastRunAt:null,lastError:null});
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]);
  const [source,setSource]=useState<'database'|'csv'>('database'),[adding,setAdding]=useState(false),[productQuery,setProductQuery]=useState(''),[itemId,setItemId]=useState(''),[options,setOptions]=useState<Candidate[]>([]),[mapping,setMapping]=useState(''),[sku,setSku]=useState('');
  const [editing,setEditing]=useState<Master|null>(null),[stock,setStock]=useState('');
  const [csv,setCsv]=useState(''),[filename,setFilename]=useState(''),[preview,setPreview]=useState<{changes:ImportRow[];checksum:string}|null>(null);
  const [confirmation,setConfirmation]=useState<{title:string;description:string;path:string;body:any}|null>(null);
  const input=useRef<HTMLInputElement>(null);
  const refresh=useCallback(async()=>{const data=await dashboardApi('/master');setRows(data.rows);setImports(data.imports);setWorker(data.worker);setSelected(old=>old.filter(id=>data.rows.some((r:Master)=>r.id===id)));},[]);
  useEffect(()=>{void refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[refresh]);
  useEffect(()=>{const t=setInterval(()=>{if(!document.hidden&&!busy)void refresh().catch(e=>setError(e.message));},10000);return()=>clearInterval(t);},[refresh,busy]);
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Operasi gagal.');}finally{setBusy(false);}}
  const filtered=rows.filter(r=>(!filter||r.status===filter)&&`${r.sku} ${r.name} ${r.variant}`.toLowerCase().includes(query.toLowerCase()));
  const visiblePage=Math.min(page,Math.max(0,Math.ceil(filtered.length/25)-1));const visible=filtered.slice(visiblePage*25,(visiblePage+1)*25);
  const candidate=options[Number(mapping)];
  async function startAdd(){await run(async()=>{const data=await dashboardApi('/products');setProducts(data.products);setAdding(true);setOptions([]);setMapping('');setSku('');setItemId('');setProductQuery('');});}
  async function loadOptions(id:string){setItemId(id);setOptions([]);setMapping('');if(!id)return;await run(async()=>{const data=await dashboardApi('/master/options?itemId='+id);setOptions(data.options);if(!data.options.length)throw Error('Shopee tidak memberikan seller stock untuk produk ini. Pemetaan tidak dapat dibuat.');});}
  async function openEdit(row:Master){await run(async()=>{await dashboardApi('/master/observe',{id:row.id,version:row.version});const data=await dashboardApi('/master');setRows(data.rows);const current=data.rows.find((r:Master)=>r.id===row.id);setEditing(current);setStock(String(current.stock));});}
  function exportTemplate(){const exportRows=selected.length?rows.filter(r=>selected.includes(r.id)):filtered.slice(0,100);if(exportRows.length>100){setError('Pilih maksimal 100 SKU per impor.');return;}downloadCsv('master-stok.csv',[['Master SKU','Stok','Versi'],...exportRows.map(r=>[r.sku,r.stock,r.version])]);setMessage(`${exportRows.length} SKU diekspor. Ubah kolom Stok saja; Versi menjaga agar data lama tidak menimpa stok baru.`);}
  async function readFile(file:File){setPreview(null);setCsv('');if(file.size>300000){setError('CSV maksimal 300 KB.');return;}await run(async()=>{const text=await file.text();const data=await dashboardApi('/master/csv/preview',{csv:text});setCsv(text);setFilename(file.name);setPreview(data);});}
  async function submit(){if(!confirmation)return;const action=confirmation;await run(async()=>{action.body.operationId||=crypto.randomUUID();await dashboardApi(action.path,{...action.body,confirm:true});setConfirmation(null);setEditing(null);setAdding(false);setPreview(null);setCsv('');setMessage(action.path==='/master/create'?'Pemetaan tersimpan. Stok Shopee belum diubah.':action.path==='/master/resolve'?'Master diperbarui mengikuti stok Shopee. Tinjau ulang sebelum mengirim perubahan baru.':'Perubahan disimpan di database online. Server akan memproses antrean meskipun PC dimatikan.');await refresh();});}
  return <section className="commerce-page master-page"><div className="commerce-page-heading"><div><span className="commerce-eyebrow">INVENTORI ONLINE</span><h1>Master produk</h1><p>Satu Master SKU untuk satu produk/variasi dan lokasi stok Shopee.</p></div><button className="commerce-button primary" disabled={busy} onClick={startAdd}>+ Hubungkan produk</button></div>
    {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="master-success" role="status">{message}</p>}
    <div className="commerce-sync-strip"><strong>Berjalan di server</strong><span>{worker.lastRunAt?`Pemeriksaan terakhir ${new Date(worker.lastRunAt).toLocaleString('id-ID')}`:'Menunggu pemeriksaan pertama'}</span><span>PC boleh dimatikan setelah perubahan tersimpan</span></div>{worker.lastError&&<p className="form-error">{worker.lastError}</p>}
    <div className="master-modes"><button className={source==='database'?'active':''} onClick={()=>setSource('database')}><strong>01 · Database online</strong><span>Edit stok per SKU, lalu kirim melalui antrean server.</span></button><button className={source==='csv'?'active':''} onClick={()=>setSource('csv')}><strong>02 · Impor CSV</strong><span>Unggah, tinjau, dan simpan perubahan ke database yang sama.</span></button></div>
    <div className="commerce-card"><h2>{source==='database'?'Perubahan stok dari master':'Impor stok dari CSV'}</h2><p>Database online selalu menjadi sumber master. CSV disimpan di server sebagai riwayat impor dan diterapkan satu kali; file lama tidak diputar ulang ketika PC mati.</p><p>Antrean diperiksa setiap 60 detik, maksimal 3 SKU per siklus. Stok Shopee dibaca bergiliran 5 SKU per siklus untuk memperbarui master. Ini pembaruan berkala, bukan real-time seketika.</p>{source==='csv'&&<><div className="commerce-filter-row"><button disabled={busy||!rows.length} onClick={exportTemplate}>↓ Template CSV {selected.length?`(${selected.length} SKU)`:'(maks. 100 SKU)'}</button><button disabled={busy} onClick={()=>input.current?.click()}>↑ Unggah & tinjau CSV</button><input hidden style={{display:'none'}} ref={input} type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void readFile(file);e.target.value='';}}/></div><p>Kolom: <code>Master SKU,Stok,Versi</code>. Maksimal 100 baris, 300 KB. Unduh template terbaru, ubah Stok, lalu unggah. Versi yang berubah akan ditolak.</p></>}</div>
    <div className="commerce-metrics">{[['Semua master',rows.length],['Dalam antrean',rows.filter(r=>['queued','processing'].includes(r.status)).length],['Sesuai Shopee',rows.filter(r=>r.status==='synced').length],['Perlu ditinjau',rows.filter(r=>r.status==='review').length]].map(([label,n])=><div className="commerce-metric" key={label}><div><small>{label}</small><strong>{loading?'—':n}</strong></div></div>)}</div>
    <div className="commerce-card"><div className="commerce-filter-row"><input aria-label="Cari master produk" placeholder="Master SKU, produk, atau variasi" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><select aria-label="Status master" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="">Semua status</option>{Object.entries(statusText).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button disabled={busy} onClick={()=>run(refresh)}>↻ Muat ulang</button>{selected.length>0&&<button onClick={()=>setSelected([])}>Hapus pilihan ({selected.length})</button>}</div>
    <div className="live-table-wrap"><table className="live-table"><thead><tr><th><input type="checkbox" aria-label="Pilih halaman master" checked={visible.length>0&&visible.every(r=>selected.includes(r.id))} onChange={e=>setSelected(old=>e.target.checked?Array.from(new Set([...old,...visible.map(r=>r.id)])):old.filter(id=>!visible.some(r=>r.id===id)))}/></th><th>Master SKU / Produk</th><th>Stok master</th><th>Stok Shopee terakhir</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={`Pilih ${r.sku}`} checked={selected.includes(r.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,r.id]:old.filter(id=>id!==r.id))}/></td><td><strong>{r.sku}</strong><small>{r.name}{r.variant?` · ${r.variant}`:''}</small><small>Item {r.itemId} · Model {r.modelId} · {r.locationId||'Lokasi default'}</small></td><td><strong>{r.stock}</strong><small>Versi {r.version} · {r.source==='csv'?'CSV':r.source==='database'?'Database':'Shopee'}</small></td><td>{r.observedStock}<small>{new Date(r.observedAt).toLocaleString('id-ID')}</small></td><td><span className={`commerce-badge ${r.status==='synced'?'green':r.status==='review'?'red':'amber'}`}>{statusText[r.status]||r.status}</span>{r.message&&<small>{r.message}</small>}</td><td><div className="master-row-actions">{source==='database'&&<button disabled={busy||r.status!=='synced'} onClick={()=>openEdit(r)}>Edit stok</button>}<button disabled={busy||['queued','processing'].includes(r.status)} onClick={()=>r.status==='review'?setConfirmation({title:'Terima stok Shopee saat ini?',description:`Master ${r.sku} akan mengikuti stok yang dibaca dari Shopee. Target lama dibatalkan; setelah ini Anda dapat membuat penyesuaian baru.`,path:'/master/resolve',body:{id:r.id,version:r.version}}):run(async()=>{await dashboardApi('/master/observe',{id:r.id,version:r.version});await refresh();})}>{r.status==='review'?'Tinjau / terima Shopee':'Periksa stok Shopee'}</button></div></td></tr>)}</tbody></table></div>
    {!loading&&!filtered.length&&<div className="commerce-empty"><h3>{rows.length?'Tidak ada hasil':'Belum ada master produk'}</h3><p>Hubungkan produk Shopee untuk membuat master. Stok awal dibaca dari Shopee, tanpa mengubah stok toko.</p></div>}<div className="commerce-pagination"><span>{filtered.length} SKU</span><button disabled={!visiblePage} onClick={()=>setPage(visiblePage-1)}>Sebelumnya</button><span>{visiblePage+1} / {Math.max(1,Math.ceil(filtered.length/25))}</span><button disabled={(visiblePage+1)*25>=filtered.length} onClick={()=>setPage(visiblePage+1)}>Berikutnya</button></div></div>
    <div className="commerce-card"><h2>Riwayat penyimpanan stok</h2><p>15 operasi terakhir. Status pengiriman masing-masing SKU dapat dilihat pada tabel master. File CSV tersimpan di server, bukan hanya di browser.</p><div className="live-table-wrap"><table className="live-table"><thead><tr><th>Waktu</th><th>Sumber</th><th>File</th><th>Jumlah SKU</th></tr></thead><tbody>{imports.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString('id-ID')}</td><td>{r.source==='csv'?'Impor CSV':'Database online'}</td><td>{r.filename||'—'}</td><td>{r.count}</td></tr>)}</tbody></table></div></div>
    {adding&&!confirmation&&<Modal title="Hubungkan Master SKU" close={()=>!busy&&setAdding(false)}><form className="panel-form" onSubmit={e=>{e.preventDefault();if(!candidate)return;setConfirmation({title:'Simpan pemetaan master?',description:`${sku} → ${candidate.name} ${candidate.variant}, lokasi ${candidate.locationId||'default'}. Stok awal ${candidate.stock} dibaca dari Shopee. Tidak ada perubahan stok yang dikirim.`,path:'/master/create',body:{sku,itemId:candidate.itemId,modelId:candidate.modelId,locationId:candidate.locationId}});}}><label>Cari produk<input value={productQuery} onChange={e=>setProductQuery(e.target.value)} placeholder="Nama atau SKU"/></label><label>Produk Shopee<select required value={itemId} disabled={busy} onChange={e=>void loadOptions(e.target.value)}><option value="">Pilih produk</option>{products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(productQuery.toLowerCase())||String(p.itemId)===itemId).map(p=><option key={p.itemId} value={p.itemId}>{p.name} · {p.itemId}</option>)}</select></label><label>Variasi / lokasi stok<select required value={mapping} onChange={e=>{setMapping(e.target.value);const c=options[Number(e.target.value)];if(c)setSku(c.shopSku&&/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(c.shopSku)?c.shopSku:`SHOPEE-${c.itemId}-${c.modelId}`);}}><option value="">Pilih variasi dan lokasi</option>{options.map((c,i)=><option key={i} value={i}>{c.variant||'Tanpa variasi'} · {c.locationId||'Default'} · Stok {c.stock}</option>)}</select></label><label>Master SKU unik<input required maxLength={80} pattern="[A-Za-z0-9][A-Za-z0-9._\-]*" value={sku} onChange={e=>setSku(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="commerce-button primary" disabled={busy||mapping===''}>Tinjau pemetaan</button></form></Modal>}
    {editing&&!confirmation&&<Modal title={`Edit stok ${editing.sku}`} close={()=>!busy&&setEditing(null)}><form className="panel-form" onSubmit={e=>{e.preventDefault();setConfirmation({title:'Kirim perubahan stok?',description:`${editing.sku}: ${editing.stock} → ${stock}. Perubahan disimpan di database online dan akan dikirim ke Shopee oleh server, meskipun halaman ditutup.`,path:'/master/update',body:{sku:editing.sku,stock:Number(stock),version:editing.version}});}}><p>{editing.name} {editing.variant}</p><label>Stok penjual di lokasi terpilih<input required type="number" min="0" max="2147483647" step="1" value={stock} onChange={e=>setStock(e.target.value)}/></label><p>Ini stok penjual, bukan stok fisik atau total seluruh gudang. Perubahan pesanan dapat terjadi saat permintaan dikirim; periksa hasil pada status master.</p><button className="commerce-button primary">Tinjau perubahan</button></form></Modal>}
    {preview&&!confirmation&&<Modal wide title={`Tinjau CSV · ${filename}`} close={()=>!busy&&setPreview(null)}><p>{preview.changes.length} baris · {preview.changes.filter(r=>r.changed).length} perubahan. File dan perubahan akan disimpan di server setelah konfirmasi.</p><div className="live-table-wrap master-preview"><table className="live-table"><thead><tr><th>Master SKU</th><th>Stok sebelumnya</th><th>Stok baru</th></tr></thead><tbody>{preview.changes.map(r=><tr key={r.sku}><td>{r.sku}</td><td>{r.previous}</td><td>{r.stock}</td></tr>)}</tbody></table></div><button className="commerce-button primary" onClick={()=>setConfirmation({title:'Simpan impor dan antrekan stok?',description:`${preview.changes.length} SKU dari ${filename}. Server akan mengirim perubahan yang valid ke Shopee. File lama tidak akan diterapkan ulang setelah proses selesai.`,path:'/master/csv/commit',body:{csv,checksum:preview.checksum,filename}})}>Lanjut ke konfirmasi</button></Modal>}
    {confirmation&&<Modal title={confirmation.title} close={()=>!busy&&setConfirmation(null)}><p>{confirmation.description}</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="commerce-filter-row"><button disabled={busy} onClick={()=>setConfirmation(null)}>Kembali</button><button className="commerce-button primary" disabled={busy} onClick={submit}>{busy?'Menyimpan…':'Konfirmasi'}</button></div></Modal>}
  </section>;
}
